### ISSUE TITLE
about the expression matrices data

### ISSUE THREAD

**Issue by lemontess** [evee-tools/evee-tools#2]
you said that by visiting the website https://portals.broadinstitute.org/evee/ , we can get the data portal and processed data, but the website can't be searched.

**Comment by jjenny** [comment]
Hi,

Because my PhD lab has closed down, I'm no longer able to host the evee website at the Broad. Sorry for any inconvenience this may have caused! I am looking for another place to host the website. In the meantime, the data can be accessed here: https://www.dropbox.com/sh/wqtydgal6l9sli5/AAAPnjFhanZ4u81L-IRYnbDPa?dl=0
